version: '2'
services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: instarails
      POSTGRES_PASSWORD: instademo
    ports:
      - '5432:5432'
    volumes:
      - instademo-postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.0.5
    ports:
      - '6379:6379' 
    volumes:
      - instademo-redis:/var/lib/redis/data

  instarails:
    build: .
    links:
      - postgres
      - redis
    volumes:
      - .:/instademo
    ports:
      - '8000:8000'
    env_file:
      - .instademo.env
    depends_on:
      - postgres
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - postgres
      - redis
    volumes:
      - .:/instademo
    env_file:
      - .instademo.env
    depends_on:
      - postgres
      - redis
