kind: Deployment
apiVersion: apps/v1
metadata:
  name: sidekiq-deployment
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  selector:
    matchLabels: 
      app: instademo
      tier: jobsqueue
  template:
    metadata:
      name: sidekiq
      labels:
        app: instademo
        tier: jobsqueue
    spec:
      containers:
      - name: sidekiq
        image: ghozlan/instarails:1.0.0
        command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "appsecrets"
              key: "DATABASE_URL"
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: "appsecrets"
              key: "SECRET_TOKEN"
        - name: JOB_WORKER_URL
          valueFrom:
            configMapKeyRef:
              name: "appconfigs"
              key: "JOB_WORKER_URL"
#        - name: RAILS_ENV
#          valueFrom:
#            configMapKeyRef:
#              name: "appconfigs"
#              key: "RAILS_ENV"