kind: Secret
apiVersion: v1
metadata:
  name: appsecrets
type: Opaque
data:
  #SECRET_TOKEN = base64(asecuretokenwouldnormallygohere)
  SECRET_TOKEN: YXNlY3VyZXRva2Vud291bGRub3JtYWxseWdvaGVyZQo=
  #DATABASE_URL = base64(postgresql://instarails:instademo@postgres:5432/instadb?encoding=utf8&pool=5&timeout=5000)
  DATABASE_URL: cG9zdGdyZXNxbDovL2luc3RhcmFpbHM6aW5zdGFkZW1vQHBvc3RncmVzOjU0MzIvaW5zdGFkYj9lbmNvZGluZz11dGY4JnBvb2w9NSZ0aW1lb3V0PTUwMDA=
  #pguser = base64(instarails)
  pguser: aW5zdGFyYWlscw==
  #pgpassword = base64(instademo)
  pgpassword: aW5zdGFkZW1v