apiVersion: v1
kind: Service
metadata:
  name: instarails-nodeport
  labels: 
    app: instademo
spec:
  type: NodePort
  ports:
    - targetPort: 8000
      port: 80
      nodePort: 30008 
  selector:
    app: instademo
    tier: app