apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  labels: 
    app: instademo
spec:
  type: NodePort
  ports:
    - targetPort: 5432
      port: 5432
      nodePort: 30009 
  selector:
    app: instademo
    tier: database